recipe: default.v1

language: pl

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 200
  - name: EntitySynonymMapper
  - name: "DucklingEntityExtractor"
    url: "http://localhost:8000"
    dimensions: ["time"]
    locale: "pl_PL"
    timezone: "Europe/Warsaw"
    timeout : 3

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 8
    epochs: 200
    constrain_similarities: true
  - name: RulePolicy
