recipe: default.v1

language: pl

pipeline:
- name: SpacyNLP
  model: "pl_core_news_sm"
- name: SpacyTokenizer
- name: SpacyEntityExtractor
- name: SpacyFeaturizer
  pooling: mean
#- name: WhitespaceTokenizer
#- name: RegexFeaturizer
#- name: LexicalSyntacticFeaturizer
#- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 300
  constrain_similarities: true
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 300
  constrain_similarities: true
#- name: "DucklingEntityExtractor"
#  url: "http://localhost:8000"
#  dimensions: ["time"]
#  locale: "pl_PL"
#  timezone: "Europe/Warsaw"
#  timeout : 3
- name: FallbackClassifier
  threshold: 0.6
  ambiguity_threshold: 0.1


policies:
- name: MemoizationPolicy
  epochs: 300
- name: RulePolicy
#- name: UnexpecTEDIntentPolicy
#  max_history: 5
#  epochs: 100
- name: TEDPolicy
  max_history: 5
  epochs: 300
  constrain_similarities: true
